/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./lib/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#5b000e",
        "primary-fixed": "#ffdad8",
        "on-secondary-fixed": "#1a1c1c",
        "primary": "#ffb3b1",
        "secondary": "#c6c6c7",
        "on-primary-fixed": "#410007",
        "on-secondary-fixed-variant": "#454747",
        "tertiary": "var(--tertiary)",
        "surface": "var(--surface)",
        "surface-container-high": "var(--surface-container-high)",
        "tertiary-fixed": "#e5e2e1",
        "on-secondary-container": "#b4b5b5",
        "background": "var(--background)",
        "tertiary-container": "#929090",
        "on-error": "#690005",
        "secondary-fixed-dim": "#c6c6c7",
        "surface-bright": "#393939",
        "primary-fixed-dim": "#ffb3b1",
        "system-red": "var(--system-red)",
        "surface-dim": "var(--surface)",
        "surface-variant": "#353535",
        "error": "#ffb4ab",
        "on-tertiary-fixed": "#1c1b1b",
        "surface-container-highest": "var(--surface-container-highest)",
        "matrix-dim": "#0D1117",
        "outline-variant": "#5b403f",
        "surface-container": "var(--surface-container)",
        "on-tertiary-container": "#2a2a2a",
        "surface-tint": "#ffb3b1",
        "inverse-surface": "#e2e2e2",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-tertiary-fixed-variant": "#474746",
        "secondary-container": "#454747",
        "on-background": "var(--on-background)",
        "on-secondary": "#2f3131",
        "surface-container-low": "var(--surface-container-low)",
        "inverse-primary": "#bb152c",
        "on-surface": "var(--on-surface)",
        "inverse-on-surface": "#303030",
        "terminal-gray": "var(--terminal-gray)",
        "on-surface-variant": "var(--on-surface-variant)",
        "on-tertiary": "#313030",
        "on-error-container": "#ffdad6",
        "primary-container": "#ff535b",
        "on-primary": "#680011",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "outline": "#ab8987",
        "secondary-fixed": "#e2e2e2",
        "error-container": "#93000a",
        "data-green": "#00FF41",
        "on-primary-fixed-variant": "#92001c"
      },
      borderRadius: {
        "DEFAULT": "0px", // As per DESIGN.md: "Shapes: Sharp (0px) corners for all primary containers, buttons, and image wrappers."
        "lg": "0px",
        "xl": "0px",
        "full": "9999px"
      },
      spacing: {
        "stack-md": "1rem",
        "stack-lg": "2rem",
        "section-gap": "4rem",
        "stack-sm": "0.5rem",
        "margin-page": "2rem",
        "gutter": "1.5rem"
      },
      fontFamily: {
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Anton", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Anton", "sans-serif"],
        "headline-lg": ["Anton", "sans-serif"],
        "headline-xl": ["Anton", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-sm": ["11px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "400" }],
        "headline-lg": ["48px", { "lineHeight": "1.1", "fontWeight": "400" }],
        "headline-xl": ["72px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.1em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
