export const siteConfig = {
  name: 'Hackeando el Sistema',
  description: 'Al Codigo Fuente de la Verdad',
  url: 'https://hackeandoelsistema.net',
  mainNav: [
    { label: 'Inicio', href: '/' },
    { label: 'Politica', href: '/category/politica/' },
    { label: 'Nacional', href: '/category/nacionales/' },
    { label: 'Internacional', href: '/category/internacionales/' },
    { label: 'Economia', href: '/category/economia-negocios/' },
    { label: 'Deportes', href: '/category/deportes/' },
    { label: 'MLB', href: '/category/mlb/' },
    { label: 'NBA', href: '/category/nba/' },
    { label: 'Clima RD', href: '/category/clima-rd/' },
    { label: 'Opinion', href: '/category/opinion/' },
    { label: 'Educacion', href: '/category/educacion/' },
    { label: 'Salud', href: '/category/salud/' },
    { label: 'Tecnologia', href: '/category/tecnologia/' },
    { label: 'Ultima Hora', href: '/category/ultima-hora/' },
  ],
};
