export const routeFixtures = [
  {
    path: '/',
    entityType: 'HOME',
    entityId: 'home',
    status: 'ACTIVE',
    httpStatus: 200,
    includeInSitemap: true,
    lastmodAt: '2026-07-07T00:00:00.000Z',
  },
  {
    path: '/category/nacionales/',
    entityType: 'CATEGORY',
    entityId: 'category-nacionales',
    status: 'ACTIVE',
    httpStatus: 200,
    includeInSitemap: true,
    lastmodAt: '2026-07-06T17:14:17.000Z',
  },
  {
    path: '/author/redaccion/',
    entityType: 'AUTHOR',
    entityId: 'author-redaccion',
    status: 'ACTIVE',
    httpStatus: 200,
    includeInSitemap: true,
    lastmodAt: '2026-07-05T01:19:10.000Z',
  },
  {
    path: '/como-recordamos-a-un-presidente-de-la-republica-dominicana/',
    entityType: 'POST',
    entityId: 'post-presidente-rd',
    status: 'ACTIVE',
    httpStatus: 200,
    includeInSitemap: true,
    lastmodAt: '2026-07-02T15:30:22.000Z',
  },
  {
    path: '/privacy-policy/',
    entityType: 'PAGE',
    entityId: 'page-privacy-policy',
    status: 'ACTIVE',
    httpStatus: 200,
    includeInSitemap: true,
    lastmodAt: '2026-07-02T19:45:58.000Z',
  },
  {
    path: '/pagina/privacy-policy/',
    entityType: 'STATIC',
    entityId: 'redirect-legacy-privacy',
    status: 'REDIRECTED',
    httpStatus: 301,
    targetUrl: '/privacy-policy/',
    includeInSitemap: false,
    lastmodAt: '2026-07-07T00:00:00.000Z',
  },
  {
    path: '/test-2/',
    entityType: 'PAGE',
    entityId: 'gone-test-page',
    status: 'GONE',
    httpStatus: 410,
    includeInSitemap: false,
    lastmodAt: '2026-07-07T00:00:00.000Z',
  },
];

export const seoMetadataFixtures = {
  '/': {
    title: 'Hackeando el Sistema',
    description: 'Al Codigo Fuente de la Verdad.',
    robotsIndex: 'INDEX',
    robotsFollow: 'FOLLOW',
    ogTitle: 'Hackeando el Sistema',
    ogDescription: 'Al Codigo Fuente de la Verdad.',
    ogImageUrl: '/logo.png',
  },
  '/category/nacionales/': {
    title: 'Nacionales - Hackeando el Sistema',
    description: 'Noticias nacionales, politica publica y actualidad dominicana.',
    robotsIndex: 'INDEX',
    robotsFollow: 'FOLLOW',
    ogTitle: 'Nacionales - Hackeando el Sistema',
    ogDescription: 'Noticias nacionales, politica publica y actualidad dominicana.',
    ogImageUrl: '/logo.png',
  },
  '/author/redaccion/': {
    title: 'Melvin Sena, autor en Hackeando el Sistema',
    description: 'Director Ejecutivo de Hackeandoelsistema.net.',
    robotsIndex: 'INDEX',
    robotsFollow: 'FOLLOW',
    ogTitle: 'Melvin Sena, autor en Hackeando el Sistema',
    ogDescription: 'Director Ejecutivo de Hackeandoelsistema.net.',
    ogImageUrl: '/logo.png',
  },
  '/como-recordamos-a-un-presidente-de-la-republica-dominicana/': {
    title: 'Como recordamos a un presidente de la Republica Dominicana',
    description: 'La historia de la Republica Dominicana no recuerda a los presidentes por sus discursos.',
    robotsIndex: 'INDEX',
    robotsFollow: 'FOLLOW',
    ogTitle: 'Como recordamos a un presidente de la Republica Dominicana',
    ogDescription: 'La historia de la Republica Dominicana no recuerda a los presidentes por sus discursos.',
    ogType: 'article',
    ogImageUrl: '/logo.png',
    schemaJson: {
      '@context': 'https://schema.org',
      '@type': 'NewsArticle',
      headline: 'Como recordamos a un presidente de la Republica Dominicana',
      datePublished: '2026-07-02T15:30:15.000Z',
      dateModified: '2026-07-02T15:30:22.000Z',
    },
  },
  '/privacy-policy/': {
    title: 'Politica de privacidad - Hackeando el Sistema',
    description: 'Politica de privacidad y tratamiento de datos de Hackeando el Sistema.',
    robotsIndex: 'INDEX',
    robotsFollow: 'FOLLOW',
    ogTitle: 'Politica de privacidad - Hackeando el Sistema',
    ogDescription: 'Politica de privacidad y tratamiento de datos de Hackeando el Sistema.',
    ogImageUrl: '/logo.png',
  },
};

export const entityFixtures = {
  'category-nacionales': {
    type: 'CATEGORY',
    title: 'Nacionales',
    description: 'Noticias nacionales, politica publica y actualidad dominicana.',
  },
  'author-redaccion': {
    type: 'AUTHOR',
    title: 'Melvin Sena',
    description: 'Director Ejecutivo de Hackeandoelsistema.net.',
  },
  'post-presidente-rd': {
    type: 'POST',
    title: 'Como recordamos a un presidente de la Republica Dominicana',
    excerpt: 'Entre la obra, los errores y el marketing.',
    content:
      'Esta es una pagina temporal de ruta SEO-safe. En la siguiente fase, el contenido vendra desde Fastify/Prisma y conservara el HTML migrado de WordPress.',
  },
  'page-privacy-policy': {
    type: 'PAGE',
    title: 'Politica de privacidad',
    content:
      'Pagina estatica temporal resuelta desde la capa de routes. El contenido final vendra del CMS.',
  },
};
